version: "3.9"

services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - monstache-network

  kibana:
    restart: always
    image: kibana:7.17.26
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - SERVER_NAME=kibana.local
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - monstache-network

  monstache:
    restart: always
    image: rwynn/monstache:rel6
    command: -f /config/monstache.config.toml
    volumes:
      - ./config/monstache.config.toml:/config/monstache.config.toml
    depends_on:
      - elasticsearch
      - mongo1
      - mongo2
      - mongo3
    networks:
      - monstache-network
    ports:
      - "8080:8080"

  mongo1:
    image: "mongo:6.0"
    ports:
      - "27020:27017"
    volumes:
      - ./mongodb/mongo1:/data/db
    networks:
      - monstache-network
    command: mongod --replSet replication

  mongo2:
    image: "mongo:6.0"
    ports:
      - "27021:27017"
    volumes:
      - ./mongodb/mongo2:/data/db
    networks:
      - monstache-network
    command: mongod --replSet replication
    depends_on:
      - mongo1

  mongo3:
    image: "mongo:6.0"
    ports:
      - "27022:27017"
    volumes:
      - ./mongodb/mongo3:/data/db
    networks:
      - monstache-network
    command: mongod --replSet replication
    depends_on:
      - mongo2

  mongosetup:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - monstache-network

networks:
  monstache-network:
    driver: bridge

